# Generated by Django 5.2.1 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='stay_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='stay_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
